#' youthu: Youth Outcomes to Health Utility
#'
#' Tools for mapping measures routinely collected in
#' youth mental health services to AQOL 6D Health Utility. Part of the
#' First Bounce model of primary youth mental health services.  This
#' development version of the youthu package has been made available as
#' part of the process of testing and documenting the package. The tools
#' contained in this development release are based on placeholder models
#' estimated from synthetic data and are for demonstration purposes only
#' - they should not yet be used to inform policy decisions. If you have
#' any questions, please contact the authors
#' (matthew.hamilton@orygen.org.au).  The documentation for this package
#' has been automatically generated by the ready4fun package and is
#' therefore quite rudimentary. Human authored documentation will follow
#' in 2021.
#'
#' To learn more about youthu, start with the vignettes:
#' `browseVignettes(package = "youthu")`
#'
"_PACKAGE"
