#' youthu: Youth Outcomes to Health Utility
#'
#' Tools for mapping measures routinely collected in youth
#' mental health services to Quality Adjusted Life Years (QALYs). Part of
#' the First Bounce model of primary youth mental health services.  This
#' development version of the youthu package has been made available as
#' part of the process of testing and documenting the package. If you
#' have any questions, please contact the authors
#' (matthew.hamilton@orygen.org.au).  The documentation for this package
#' has been automatically generated by the ready4fun package and is
#' therefore quite rudimentary. Further human authored documentation will
#' follow in 2021.
#'
#' To learn more about youthu, start with the vignettes:
#' `browseVignettes(package = "youthu")`
#'
"_PACKAGE"
