#' map2aqol: Map Measures Routinely Collected in Mental Health
#' Services to AQOL 6d Health Utility.
#'
#' Tools for mapping measures routinely collected in
#' youth mental health services to AQOL 6D Health Utility. Part of the
#' First Bounce model of primary youth mental health services.  This
#' development version of the map2aqol package has been made available as
#' part of the process of testing and documenting the package. The tools
#' contained in this development release automate a number of tasks which
#' MODIFY THE DIRECTORY STRUCTURE OF YOUR LOCAL MACHINE.  Therefore you
#' should only trial this software if you feel confident that you
#' understand what it does and have created a sandpit area in which you
#' can safely undertake testing. If you have any questions, please
#' contact the authors (matthew.hamilton@orygen.org.au).  The
#' documentation for this package has been automatically generated by the
#' ready4fun package and is therefore quite rudimentary. Human authored
#' documentation will follow in 2021.
#'
#' To learn more about map2aqol, start with the vignettes:
#' `browseVignettes(package = "map2aqol")`
#'
"_PACKAGE"
